Name               = "Wordpress"
Env                = "Dev"
Created_by         = "Janna"
Dept               = "IT"
ami                = "ami-0b898040803850657"
instance_type      = "t2.micro"
key_name           = "winkey-terraf"
count              = "3"